server:
  port: 8085

spring:
  application:
    name: wallet-service
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/wallet_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Frustum@7#}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

gateway:
  secret: booknest-gateway-internal-secret-key-2026-secure-abcdef123456

razorpay:
  key: ${RAZORPAY_KEY:}
  secret: ${RAZORPAY_SECRET:}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql:3306/wallet_db?createDatabaseIfNotExist=true
  
  rabbitmq:
    host: rabbitmq

eureka:
  instance:
    hostname: wallet-service
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

logging:
  level:
    root: INFO
    com.booknest: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"